FROM alpine:3.17
RUN apk add --update nodejs npm
RUN npm install -g pnpm
RUN mkdir -p /home/ooneex/app
COPY config/esbuild.config.js /home/ooneex/esbuild.js
RUN chmod +x /home/ooneex/esbuild.js

RUN addgroup -S ooneex && adduser -S ooneex -G ooneex
USER ooneex
RUN touch /home/ooneex/.shrc

RUN touch /home/ooneex/tw-watch.sh
RUN chmod +x /home/ooneex/tw-watch.sh
RUN echo "npx tailwindcss -c app/config/tailwind.config.js -i app/static/styles/app.css -o app/static/dist/app.css --watch" >> /home/ooneex/tw-watch.sh

RUN touch /home/ooneex/tw-build.sh
RUN chmod +x /home/ooneex/tw-build.sh
RUN echo "npx tailwindcss -c app/config/tailwind.config.js -i app/static/styles/app.css -o app/static/dist/app.css --minify" >> /home/ooneex/tw-build.sh

WORKDIR /home/ooneex
# RUN cd /home/ooneex
RUN pnpm add solid-js
RUN pnpm add -D tailwindcss esbuild esbuild-plugin-solid babel-preset-solid
RUN #touch .babelrc
RUN echo '{ "presets": ["solid"], "plugins": [] }' >> .babelrc
RUN touch tsconfig.json
RUN echo '{ "compilerOptions": { "jsx": "preserve", "jsxImportSource": "solid-js" } }' >> tsconfig.json
# RUN npx tailwindcss init
# RUN mkdir -p static
# RUN mv tailwind.config.js static/tailwind.config.js
