import {
  AppEnvType,
  AppLocaleType,
  AppVersionType,
  HandlerType,
  HttpMethodType,
  HttpProtocolType,
  MiddlewareType,
  ViewType,
} from "../deps.ts";

export type RouteConstraintsType = {
  where?: Record<string, string | number>;
  regex?: Record<string, string>;
  number?: string[];
  alphaNumeric?: string[];
  in?: Record<string, (string | number)[]>;
};

export type RouteDefinitionType = {
  /**
   * Name of route
   */
  name: string;
  /**
   * Path schema
   * @example /products/:id /users/:id/edit
   */
  path: string;
  /**
   * View to render if this route matched
   */
  view?: ViewType;
  /**
   * Handler to trigger if this route matched
   */
  handler: HandlerType;
  /**
   * Middlewares to trigger if this route matched
   */
  middlewares?: MiddlewareType[];
  /**
   * If Content-Security-Policy should be enabled for this page. If 'true', a
   * locked down policy will be used that allows only the scripts and styles
   * that are generated by fresh. Additional scripts and styles can be added
   * using the `useCSP` hook.
   */
  csp?: boolean;
  /**
   * Allowed methods for this route
   */
  methods?: HttpMethodType[];
  /**
   * Protocol type
   * @example https http
   */
  protocols?: HttpProtocolType[];
  /**
   * Allow hosts for this route
   * @example ["api.ooneex.io"]
   */
  hosts?: string[];
  /**
   * Allow ips for this route
   * @example ["127.0.0.1"]
   */
  ips?: string[];
  /**
   * Port of route
   * @default 80
   * @example 8000
   */
  ports?: string[];
  /**
   * Constraints for route params
   * @example {id: /^[0-9]+$/}
   */
  constraints?: RouteConstraintsType;
  /**
   * Default values for route params
   */
  default?: Record<string, string | number>;
  /**
   * Additional data for this route
   */
  data?: Record<string, unknown>;
  /**
   * Allowed locales for this route
   */
  locales?: AppLocaleType[];
  /**
   * Allowed environment for this route
   * @example ["dev"] ["prod", "dev"] ["test", "demo"]
   */
  envs?: AppEnvType[];
  /**
   * Version of this route
   */
  versions?: AppVersionType[];
  /**
   * Render fixture for this route
   */
  fixture?: string;
  /**
   * Route description. Used for documentation
   */
  description?: string;
};

export interface IRoute {
  getName: () => string;
  getPath: () => string;
  getProtocols: () => HttpProtocolType[] | null;
  getHosts: () => string[] | null;
  getIps: () => string[] | null;
  getPorts: () => string[] | null;
  getDefault: () => Record<string, string | number> | null;
  getConstraints: () => RouteConstraintsType | null;
  getView: () => ViewType | null;
  getHandler: () => HandlerType;
  getMiddlewares: () => MiddlewareType[] | null;
  getMethods: () => HttpMethodType[] | null;
  getData: <T>() => Record<string, T> | null;
  getLocales: () => AppLocaleType[] | null;
  getEnvs: () => AppEnvType[] | null;
  getVersions: () => AppVersionType[] | null;
  getFixture: () => string | null;
  getDescription: () => string | null;
}
